### ISSUE TITLE
System.Net.Sockets.SocketException on Mono

### ISSUE THREAD

**Issue by mezz64** [bp2008/cameraproxy#1]
I'm attempting to get this working through Mono in a docker container, but get a continuous stream of exceptions like the one below.  Functionality is fine, but the constant error logging is sucking up memory over time.
```
Exception thrown at 04/29/2017 01:11:28
System.IO.IOException: Write failure ---> System.Net.Sockets.SocketException: Connection reset by peer
  at System.Net.Sockets.Socket.Send (System.Byte[] buffer, Int32 offset, Int32 size, SocketFlags flags) <0x40f64820 + 0x000e7> in <filename unknown>:0 
  at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, Int32 offset, Int32 size) <0x40f64630 + 0x000a7> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.Write (System.Byte[] buffer, Int32 offset, Int32 size) <0x40f64630 + 0x0011f> in <filename unknown>:0 
  at System.IO.StreamWriter.Flush (Boolean flushStream, Boolean flushEncoder) <0x2af3d3e3fda0 + 0x000fa> in <filename unknown>:0 
  at System.IO.StreamWriter.Flush () <0x2af3d3e3fd70 + 0x0001f> in <filename unknown>:0 
  at MJpegCameraProxy.MJpegServer.handleGETRequest (SimpleHttp.HttpProcessor p) <0x40f3dda0 + 0x00c1a> in <filename unknown>:0 
```

**Comment by bp2008** [comment]
I bet whatever code I wrote to swallow those errors isn't applying to the different error messages that mono has.  Are there any other messages besides that one? "Write failure ---> System.Net.Sockets.SocketException: Connection reset by peer"

**Comment by mezz64** [comment]
That's the only one. It repeats pretty much every second.  Always write, never read.

I have 2 cameras configured, and am requesting mjpg streams for each of them.  Doing some googling it looks like it might be this line with ```Thread.Sleep```, but it looks like it's inside the try block so maybe not.
https://github.com/bp2008/cameraproxy/blob/master/MJpegCameraProxy/MJpegCameraProxy/MJpegServer.cs#L148

Is there a switch parameter to disable logging?  Since there are no functionality problems I think killing the logging will at least fix the memory leak.

**Comment by bp2008** [comment]
There isn't one.  Perhaps you could set the log file to read only, though?  And then the logging should silently fail.

**Comment by bp2008** [comment]
The exception message suggests this is happening during a Flush() call.  And if it is happening every second then I'm betting whatever client (a web browser?) you are using is restarting the stream every second for some reason.  Likely a broken implementation of mjpeg.

**Comment by mezz64** [comment]
The read only logging idea is a good one, fortunately your other suggestion of investigating the client helped squash the error all together.  It was doing some weird things pulling a single image from the mjpg stream that was causing the error to happen.

**Comment by bp2008** [comment]
You can expect to still see this exception message, though, since it is fairly standard for a TCP connection to end in an exception.  But once per second is pretty excessive :)
