### ISSUE TITLE
No idle timout

### ISSUE THREAD

**Issue by Jacob-Roberts** [bp2008/cameraproxy#11]
Is there any way to have the web page not timeout and show the video indefinitely?

**Comment by bp2008** [comment]
Which page?  If I recall, most of the pages do have a URL parameter you can set to achieve this.

**Comment by Jacob-Roberts** [comment]
The page to view the camera. In my instance, it is a camera being loaded over RTSP using the VLC Transcoder. 

![Capture](https://user-images.githubusercontent.com/1888257/57386943-ac27a300-7172-11e9-86f0-2097f423b846.PNG)

**Comment by bp2008** [comment]
Try http://localhost:44456/image/andchangemyid.cam?override=1

**Comment by Jacob-Roberts** [comment]
That works! Thank you!
