### ISSUE TITLE
HTTPS Setup

### ISSUE THREAD

**Issue by bluedoggy731** [bp2008/cameraproxy#12]
Hi, I'm trying to get https set up.
I had it set up for 1.3.8 but updating to 1.7 I'm not sure where to set it in the config (in the cfg file?).

Would appreciate it if there could be pointers. Many thanks.

**Comment by bp2008** [comment]
You should be able to configure it something like this, though in the ONE installation I still occasionally use of this program, I don't even use https so I can't be 100% sure it still works.
```
  <webport_https>443</webport_https>
  <certificateMode>SelfSigned</certificateMode>
```

**Comment by bp2008** [comment]
Yeah this should still work.  It does for me.
