### ISSUE TITLE
If camera doesn't support Mjpeg or jpeg can use other?

### ISSUE THREAD

**Issue by jerryamile** [bp2008/cameraproxy#13]
Sorry bother, not sure where to ask this, I know there is no new development happening, but I'm excited to try this program out. I've been unsuccessful in adding my hikvision or dahau cameras using Jpeg snapshot or mjpeg, not sure if they support it, can I use the RTSP instead? More overhead for the CPU right? how about for clients connecting to the cameraproxy, will the output be only jpeg or mjpeg, there is no other output stream available, correct?

Thanks so much
Jerry

**Comment by bp2008** [comment]
That is right.  If you use `vlc_transcode` as the camera type then it should work with RTSP.  The output will still only be jpeg or mjpeg.
