### ISSUE TITLE
Unable to get Pan/Tilt functioning with Amcrest Cam and CustomPTZProfile

### ISSUE THREAD

**Issue by MLBZ521** [bp2008/cameraproxy#2]
Hey,

I've been trying to get the Pan/Tilt to work on an Amcrest Camera (model:  IP2M-841) on and off for the last couple weeks.  I can make the camera move with via the 'API' calls in a browsers, but not with a CustomPTZProfile.

It always fails with this:
```
Exception thrown at 6/4/2017 11:53:10 PM
Additional information: SimpleProxy URL: http://192.168.0.101/cgi-bin/ptz.cgi?action=start&channel=1&code=Up&arg1=0&arg2=1&arg3=0
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at MJpegCameraProxy.SimpleProxy.GetResponse(HttpWebRequest webRequest)
   at MJpegCameraProxy.SimpleProxy.GetData(String url, String user, String password, Boolean keepAlive, Boolean allowErrorLogging)
```

Working API call is:
```
http://192.168.0.101/cgi-bin/ptz.cgi?action=start&channel=1&code=Up&arg1=0&arg2=1&arg3=0
```
After sending the above line in a browser, it asks for authentication details.

Do you have any suggestions regarding this?

Thanks!

**Comment by bp2008** [comment]
You probably have not set the **PTZ User Name** and **PTZ Password** fields in that camera configuration.  It will use whatever you set there.

**Comment by MLBZ521** [comment]
I forgot to mention that.  I do have the PTZ Host Name, User Name, and Password fields set.

I receive the same `Exception thrown` error as above when using the correct password and a 'bad' password.

**Comment by bp2008** [comment]
I'm not sure what is wrong then.  Could you screenshot your camera configuration and custom ptz profile pages?

**Comment by MLBZ521** [comment]
I have two different brand cameras that I've tested, the Amcrest and an older Foscam.  I was able to get the Foscam to work correctly with a Custom PTZ Profile.  (I did have to specify a port before it worked.)

I've taken some screen shots of my config as requested (ignore the quality, they were taken remotely connected to my machine at home).

Cam Config:
![cam config](https://cloud.githubusercontent.com/assets/29153760/26799303/d5e1e6a4-49e9-11e7-8d7d-b330da905104.png)

PTZ Profile:
![ptz profile](https://cloud.githubusercontent.com/assets/29153760/26799316/e3a5e326-49e9-11e7-956b-12d03b054ea2.png)

I was testing with this profile, so you can ignore the obviously wrong syntax for some of the commands.

Wrong command, I get this response:
```
Exception thrown at 6/5/2017 12:06:47 PM
Additional information: SimpleProxy URL: http://10.0.0.14/ptz.cgi?command=right
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at MJpegCameraProxy.SimpleProxy.GetResponse(HttpWebRequest webRequest)
   at MJpegCameraProxy.SimpleProxy.GetData(String url, String user, String password, Boolean keepAlive, Boolean allowErrorLogging)
```

Correct command, I get this:
```
Exception thrown at 6/5/2017 12:06:48 PM
Additional information: SimpleProxy URL: http://10.0.0.14/cgi-bin/ptz.cgi?action=stop&channel=1&code=Up&arg1=5&arg2=1&arg3=0
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at MJpegCameraProxy.SimpleProxy.GetResponse(HttpWebRequest webRequest)
   at MJpegCameraProxy.SimpleProxy.GetData(String url, String user, String password, Boolean keepAlive, Boolean allowErrorLogging)
```

I was playing with Fiddler last night to see what was being sent and received, if you think that data would be of help, I can provide that.

**Comment by MLBZ521** [comment]
Did a little more testing and digging...

If I set the PTZ Host Name to:  `admin:password@10.0.0.14` and try running that with the same PTZ Profile, I get this erorr:
```
Exception thrown at 6/5/2017 1:18:52 PM
Additional information: SimpleProxy URL: http://admin:password@10.0.0.14/cgi-bin/ptz.cgi?action=stop&channel=1&code=Up&arg1=5&arg2=1&arg3=0
System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at MJpegCameraProxy.SimpleProxy.GetResponse(HttpWebRequest webRequest)
   at MJpegCameraProxy.SimpleProxy.GetData(String url, String user, String password, Boolean keepAlive, Boolean allowErrorLogging)
```

So even passing it through way, it's still `(401) Unauthorized`.  If I copy that string into my browser, it works fine -- which I'm assuming your code isn't executing it just like that, so probably irrelevant.  (I did clear the PTZ username and password fields.)

Either way, this may be more helpful...  Found what sounds like a similar issue on ZoneMinder forums regarding someone with an Auth issue as well..  Possibly a change in the latest firmware it sounds like?

Here's the link:  https://forums.zoneminder.com/viewtopic.php?f=9&t=25606
If you look for the posts started by "Gilley7997", that's where the topic starts.  The second page has some people confirming success with the previous version, R16.

I'll downloaded it and will try rolling back when I get home tonight, unless you have any other recommendations?

**Comment by bp2008** [comment]
Well that all looks good, so I'm guessing the camera does not support http basic authentication, and wants "digest" authentication instead.  Which is unfortunate for two reasons.  1) This program is using basic authentication. 2) Having this do digest authentication instead is easy enough, but it will add some delay to your PTZ commands as it will have to connect twice for each command.

Do you have Visual Studio or do I need to patch this thing to allow digest authentication in SimpleProxy.cs?

**Comment by MLBZ521** [comment]
The double connections would match what I was seeing with Fiddler last night then.

Yea, that seems to be the issue:  
- https://amcrest.com/forum/technical-discussion-f3/cgi-sdk-no-longer-functioning-on-17r--t2401.html
- https://github.com/tchellomello/python-amcrest/issues/70

I assume you'd want to implement as an if basic fails, try digest...  Or would it be more _efficient_ to make 'authentication type' a configurable option in the cam config;  set type as basic or digest authentication?

I see where you're setting the authentication to "Basic" in SimpleProxy.cs, but unfortunately, I'm not a programmer.  I've taken a few classes and I can script (PowerShell, Bash/Shell, etc) and I can read code to understand what it's doing to varying degrees, but that's about as far as I can get myself without direction.

**Comment by bp2008** [comment]
I believe for digest authentication to work, the client needs to receive a challenge from the server and use it to build the response.

I'll build you a little patch to try.

**Comment by bp2008** [comment]
~snip~

Try that and let me know how it goes.  In theory it should try basic authentication and automatically fall back to digest.  But for all I know it will just throw an exception instead.

**Comment by MLBZ521** [comment]
Thanks for the quick patch! However, unfortunately I can't get the service to start with the new executable.

Any suggestions?

**Comment by bp2008** [comment]
Oops, I gave you a 64 bit executable when the releases are all 32 bit.  This one should work:

[MJpegCameraProxy 1.6.4.1.zip](https://github.com/bp2008/cameraproxy/files/1055214/MJpegCameraProxy.1.6.4.1.zip)

**Comment by MLBZ521** [comment]
Works great!  Thanks!

I don't really notice a difference in response compared to the older Foscam.  So that's good.  I don't think it likes directional movement 'clicks' in rapid succession though.

**Comment by MLBZ521** [comment]
Still working great, so I'll go ahead and close this issue.  Thanks again! 👍
