### ISSUE TITLE
Service Wont Start, Failed to respond to command 

### ISSUE THREAD

**Issue by ccm1495** [bp2008/cameraproxy#3]
Service Wont Start, Failed to respond to command in timely manor 

New install Windows 7

**Comment by bp2008** [comment]
Try the executable ending in "Cmd", as that is the command line version and if something is wrong you should hopefully see it in the output.

**Comment by ccm1495** [comment]
The cmd executable works fine, the other executable that is called on by the service fails to open and invokes Windows's aplication has closed troubleshoot message

**Comment by ccm1495** [comment]
This was working fine on this same server around a week ago

**Comment by bp2008** [comment]
Hmm.

Have you looked in the error log (text file)?  Maybe it is logging something there when it fails to start.
