### ISSUE TITLE
BPUtil Assembly missing

### ISSUE THREAD

**Issue by perezale** [bp2008/cameraproxy#4]
Hey!
I´m trying to run cameraproxy with mono in ubuntu 16.04, but when running mono MJpegCameraProxyCmd.exe I get an assembly missing error

I saw the notice to add BPUtils for building CameraProxy from source, but as I´m just trying to run it, I think something is missing. Shouldn't this assembly be included in the release?

Here's the error
`$ mono MJpegCameraProxyCmd.exe         
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'MJpegCameraProxy.MJpegWrapper:httpServer' (1) due to: Could not load file or assembly 'BPUtil, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:BPUtil, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:<none>
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'MJpegCameraProxy.MJpegWrapper:httpServer' (1) due to: Could not load file or assembly 'BPUtil, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:BPUtil, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:<none>`

What do you think? Thanks!

**Comment by bp2008** [comment]
I haven't tried running this in linux in quite a while.  I guess I need to do that and see if I have the same problem.

**Comment by perezale** [comment]
OK, let me know what can I help you with.
you used static linking for BPUtils distribution, don't you? I could try exporting the dll and see the results

Btw, 1.6.4 runs ok. So it comes from 1.6.5 refactor. Maybe it deserved a higher version change.

**Comment by bp2008** [comment]
.NET doesn't do static linking.  I used https://github.com/Fody/Costura to embed the managed dlls.

Most likely I didn't set a flag I needed to set for it to work with linux and mono.

**Comment by bp2008** [comment]
You may want to try version 1.7.  I haven't tested the results but I changed a couple of things that might have fixed the problem.

https://github.com/bp2008/cameraproxy/releases

**Comment by perezale** [comment]
Works like a charm! Thank you! 
I've tested it under Ubuntu Server 16.04 with mono-service

Great job!

**Comment by bp2008** [comment]
Excellent!
