### ISSUE TITLE
VLC transcode generating slightly corrupted images

### ISSUE THREAD

**Issue by perezale** [bp2008/cameraproxy#6]
Hi, once again :) 

I'm testing a windows based CameraProxy setup (both 1.6.4 & 1.7) reading a 1280x720  rtsp h264 stream from a Hikvision DS-2CD2622FWD-IZNS camera. 

The problem is that **some** images (occurs sometimes, not always) get a slight but still annoying shift, particularly on moving objects.

The camera connects directly to the PC via a dedicated ETH interface. The PC running CameraProxy is a Intel Core i5 4200U - 4GB and the proxy & camera setup is as follows:

[CameraProxy camera settings](http://imgur.com/a/jCG4x)
[Hikvision Settings](http://imgur.com/a/D95XP)

Examples images (Check the cars): 
http://imgur.com/a/WyU0W
http://imgur.com/a/kFF4W
http://imgur.com/a/jCG4x

I tried to increase the buffer time and lowering transcode frame rate limit but had no luck with these.

Any ideas on what could be causing this behaviour ? 

Sorry for every report, I think this project is a great contribution to the open source community and that's why I care about it and want it to be better every day.

**Comment by bp2008** [comment]
Heh.

Looks like the video is tearing.  Like what happens when you render a video game at a higher frame rate than the monitor's refresh rate.  I haven't seen that happen with an IP camera before.

I have no idea what is causing it, but I highly doubt it is cameraproxy's fault, and probably not even VLCs. 
 I suspect the camera is actually encoding frames that way.

**Comment by bp2008** [comment]
Also, I have mostly stopped development on this project.  Feel free to continue submitting bugs when you find them, but I don't intend to add more camera-related features or spend a lot of time on it.

**Comment by perezale** [comment]
That's ok.  As you mention, I believe this is the first time I see this behaviour.
Don't worry, the tool is quite useful as it is right now. We'll see how it evolves within Github community.
I appreciate you work and support. I'll close the issue as for now it's not CameraProxy's problem.
Thanks!
