### ISSUE TITLE
Global Throttled Stream

### ISSUE THREAD

**Issue by ghost** [bp2008/cameraproxy#7]
-------------
Exception thrown at 16.09.2017 19:12:46
System.IO.IOException: In die Übertragungsverbindung können keine Daten geschrieben werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
   bei System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   bei System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   bei System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   bei BPUtil.SimpleHttp.GlobalThrottledStream.ThrottlingManager.ThrottledWrite(GlobalThrottledStream stream, Byte[] buffer, Int32 offset, Int32 count) in C:\Users\brpea\Source\Repos\BPUtil\BPUtil\SimpleHttp\GlobalThrottledStream.cs:Zeile 342.
   bei BPUtil.SimpleHttp.GlobalThrottledStream.Write(Byte[] buffer, Int32 offset, Int32 count) in C:\Users\brpea\Source\Repos\BPUtil\BPUtil\SimpleHttp\GlobalThrottledStream.cs:Zeile 76.
   bei System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   bei System.IO.StreamWriter.Flush()
   bei MJpegCameraProxy.MJpegServer.handleGETRequest(HttpProcessor p)
-------------
-------------
Exception thrown at 16.09.2017 19:12:47
System.IO.IOException: In die Übertragungsverbindung können keine Daten geschrieben werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
   bei System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   bei System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   bei System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   bei System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   bei BPUtil.SimpleHttp.GlobalThrottledStream.ThrottlingManager.ThrottledWrite(GlobalThrottledStream stream, Byte[] buffer, Int32 offset, Int32 count) in C:\Users\brpea\Source\Repos\BPUtil\BPUtil\SimpleHttp\GlobalThrottledStream.cs:Zeile 342.
   bei BPUtil.SimpleHttp.GlobalThrottledStream.Write(Byte[] buffer, Int32 offset, Int32 count) in C:\Users\brpea\Source\Repos\BPUtil\BPUtil\SimpleHttp\GlobalThrottledStream.cs:Zeile 76.
   bei System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   bei System.IO.StreamWriter.Flush()
   bei MJpegCameraProxy.MJpegServer.handleGETRequest(HttpProcessor p)
-------------

**Comment by bp2008** [comment]
Oh, the dangers of suppressing event logs based on string comparisons.

I'm sorry for the inconvenience this causes for you.
