### ISSUE TITLE
System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by aron7676** [bp2008/cameraproxy#8]
Server was running exceptionally for a week or so. rebooted the cameraproxy service after rebooting computer, and it crashes every time I try to start it now. 

This is the error that I am getting, and it errors out with "unhandled exception" for both the GUI and the cmd applet.

System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by bp2008** [comment]
Something else is using the port cameraproxy is configured to listen on.  Most likely it is a hung cameraproxy instance, but it could be anything.

Reboot again.  If it happens again, check Windows' Resource Monitor > Network tab, where you can look at a list of Listening Ports to find the culprit.

**Comment by aron7676** [comment]
That was the problem. It was persisting through reboots, but clearing it that way worked. Thanks a ton, been beating my head against this for HOURS.
