### ISSUE TITLE
RTSP streams requiring password

### ISSUE THREAD

**Issue by Sukasa** [bp2008/cameraproxy#9]
Is there a way to specify a password required for an RTSP stream?  I have some IP cameras to integrate to that won't seem to do unauthenticated RTSP streams

**Comment by bp2008** [comment]
Yeah I think it will take the user name and password in the URL like this:

rtsp://user:pass@192.168.0.1/

**Comment by Sukasa** [comment]
Thanks, I apologize for the trouble
